spring:
  mail:
    host: smtp.163.com
    username: w100432249@163.com
    password: ZSHUFXQBATSZGZGP
  rabbitmq:
    addresses: localhost
    username: guest
    password: guest
    virtual-host: /
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medical_management?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  security:
    filter:
      order: -100
    jwt:
      key: abcdef
      expire: 7
#    user:
#      name: root
#      password: root
  data:
    redis:
      port: 6380