spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/medical_management?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  security:
    jwt:
      key: abcdefg
      expire: 7
    user:
      name: root
      password: root